### ISSUE TITLE
Azure Notebooks no longer exist...

### ISSUE THREAD

**Issue by eavanvalkenburg** [MicrosoftDocs/architecture-center#3773] opened 2022-11-08 09:20 UTC
[Enter feedback here]
This page mentions Azure Notebooks which is no longer available, but instead spread throughout vscode, AML and Github.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97abbeb4-6c20-4dfd-8a3f-3b448919679c
* Version Independent ID: d979d82d-2e80-5a1e-7928-7f8154ed34f3
* Content: [Choose a data analytics and reporting technology - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/analysis-visualizations-reporting)
* Content Source: [docs/data-guide/technology-choices/analysis-visualizations-reporting.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/technology-choices/analysis-visualizations-reporting.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by mumurug-MSFT** [comment] 2022-11-08 14:21
@eavanvalkenburg Thanks for the feedback. I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by eavanvalkenburg** [comment] 2022-11-21 08:37
Just noticed this is a duplicate of #3172 which was raised a year ago, please fix!

**Comment by hallihan** [comment] 2022-12-05 17:50
Closing as duplicate of #3172 - Internal tracking: https://dev.azure.com/MSFT-SKILLING/Content/_workitems/edit/24500

**Closed by hallihan** 2022-12-05 17:50 UTC
Labels: doc-enhancement, assigned-to-author, triaged, architecture-center/svc, Pri2, azure-guide/subsvc
