### ISSUE TITLE
Service Incident/Outage Clarity

### ISSUE THREAD

**Issue by bernaljo** [MicrosoftDocs/architecture-center#3895] opened 2023-02-08 21:22 UTC
This document is still unclear when there is a service failure or regional outage impacting down time in ADF and Synapse functions.
Customers need more clarity that although we have a failover process, there is a possibility of service interruption. 

This section explains that failures are seamless:

When a datacenter, part of a datacenter, or an availability zone in a region goes down, failover happens with zero downtime for zone-resilient Data Factory and Azure Synapse pipelines.

Only later does it warn of possible occurrences. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b1b3a84-dc5b-6486-658a-faed8b124534
* Version Independent ID: 4b1b3a84-dc5b-6486-658a-faed8b124534
* Content: [BCDR for Azure Data Factory and Azure Synapse Analytics pipelines - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/analytics/pipelines-disaster-recovery)
* Content Source: [docs/example-scenario/analytics/pipelines-disaster-recovery.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/analytics/pipelines-disaster-recovery.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @ssabat
* Microsoft Alias: **susabat**

**Comment by ManoharLakkoju-MSFT** [comment] 2023-02-09 03:18
@bernaljo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment] 2023-05-15 11:39
Hi @bernaljo
For any zone resilient resource, zero down time is expected behavior. ADF still cannot be assigned to a Zone by design. It is region specific.  It is zone failure tolerant i.e if a dependent service fails in a zone, it can reuse services in alternate zone automatically. 

I will close the ticket, but feel free to open a new one if you still have concerns

#please-close

**Closed by v-fearam** 2023-05-15 11:39 UTC
Labels: assigned-to-author, triaged, product-question, architecture-center/svc, example-scenario/subsvc, Pri2
