### ISSUE TITLE
Updated Azure Databricks icon

### ISSUE THREAD

**Issue by clintonwford** [MicrosoftDocs/architecture-center#2794] opened 2021-04-29 15:40 UTC
Hi, could you help me update the Azure Databricks icon on [this diagram](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/images/stream-processing-databricks.png) on the [Stream Processing with Azure Databricks](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/stream-processing-databricks) architecture with this new SVG file: https://drive.google.com/file/d/13z9cECUZsyu8ZjWzHErUZbAhuO_jXlUK/

Thank you,

Clinton Ford
Principal Product Marketing Manager
Databricks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42385d9e-bf16-c83f-4cc4-bc7819b7c72a
* Version Independent ID: 8ff90608-83ab-fe3f-c01a-5e4e288f28fc
* Content: [Stream processing with Azure Databricks - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/stream-processing-databricks#feedback)
* Content Source: [docs/reference-architectures/data/stream-processing-databricks.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/data/stream-processing-databricks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment] 2021-04-29 15:40
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/418451/>418451</a>

**Comment by neilpeterson** [comment] 2021-05-12 17:34
Looks like a dupe of https://github.com/MicrosoftDocs/architecture-center/issues/2795. Closing here.

**Comment by clintonwford** [comment] 2021-05-12 17:38
This is a very similar issue as #2795, but for a different architecture.

**Comment by neilpeterson** [comment] 2021-05-12 17:42
Thanks @clintonwford taking a closer look.

**Comment by BryanLa** [comment] 2022-09-28 19:46
@clintonwford - our apologies for the long delay, and thank you for the contribution.

This work is complete and will republish around 3pm Pacific today.

#please-close

**Closed by BryanLa** 2022-09-28 19:46 UTC
Labels: doc-bug, assigned-to-author, triaged, architecture-center/svc, reference-architecture/subsvc, Pri2
