### ISSUE TITLE
Broke links "What's new in the Azure Architecture Center"

### ISSUE THREAD

**Issue by romulobrandino** [MicrosoftDocs/architecture-center#2342] opened 2020-08-26 02:24 UTC
The links for Architecture in **"What's new"** are broke, 404 - Page not found.

Example:

https://docs.microsoft.com/en-us/azure/architecture/changelog#new-articles

**Comment by absheik** [comment] 2020-08-26 02:25
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by PramodValavala-MSFT** [comment] 2020-08-26 04:10
@romulobrandino Thanks for catching that! We have assigned this issue to the content author to review and update accordingly.

@absheik Looks like this file is generated. Could you please take a look at how we can fix this?

**Comment by cyberjacob** [comment] 2020-09-03 08:57
This is affecting all links on the changelog page, appears to have been caused by 3c14132

**Comment by ckittel** [comment] 2020-09-09 17:12
Thank you all for bringing this to our attention.  The links have been corrected.

**Closed by ckittel** 2020-09-09 17:12 UTC
Labels: Pri3, assigned-to-author, doc-bug, triaged
