### ISSUE TITLE
Error while establishing connectivity between spokes

### ISSUE THREAD

**Issue by fawohlsc** [MicrosoftDocs/architecture-center#1852] opened 2019-11-13 01:14 UTC
Establishing a connectivity between spokes via `Test-NetConnection 10.2.0.36 -CommonTCPPort RDP` results in issue `error: building block for parameter 'Template' was not found.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87139748-938e-638e-de1f-94f8becfe1da
* Version Independent ID: b96371e6-defb-3e70-792a-2c0cfdc25b7d
* Content: [Implement a hub-spoke network topology - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services)
* Content Source: [docs/reference-architectures/hybrid-networking/shared-services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/shared-services.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment] 2019-11-13 05:59
@fawohlsc Thank you for your question! Since this channel is for driving improvements towards MS Docs, could you provide the URL of the specific documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team.

**Comment by fawohlsc** [comment] 2019-11-13 18:03
Hey @KetanChawda-MSFT - here you go and thanks for the quick reply: https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services

**Comment by absheik** [comment] 2020-01-06 22:31
AB#160219 - Thanks for reporting - this issue is under review

**Comment by absheik** [comment] 2020-04-08 18:38
Unable to reproduce this issue.  Closing Issue as no repro.

**Closed by absheik** 2020-04-08 18:38 UTC
Labels: Pri3, architecture-center/svc, assigned-to-author, needs-more-info, reference-architecture/subsvc, triaged
