### ISSUE TITLE
How to do custom routing?

### ISSUE THREAD

**Issue by kudlatiger** [MicrosoftDocs/architecture-center#2377] opened 2020-09-10 16:53 UTC
[What if I want to have custom routing instead of load balancer routing?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b8e780c-8b2b-f579-d380-a33cb76f0e82
* Version Independent ID: e666a3fc-cb2e-30a8-c4ab-b8db700e05cb
* Content: [IaaS: Web application with relational database - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/high-availability/ref-arch-iaas-web-and-db)
* Content Source: [docs/high-availability/ref-arch-iaas-web-and-db.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/high-availability/ref-arch-iaas-web-and-db.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Maggsl
* Microsoft Alias: **pnp**

**Comment by absheik** [comment] 2020-09-10 16:54
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#299612

**Comment by ckittel** [comment] 2020-09-10 19:45
@kudlatiger thanks for the question; can you say more about your situation?

I'll take a stab at your question, but I might be off the mark here without the added context.  Let me know.

Thought 1:
Azure Application Gateway can perform layer-7-based traffic routing needs, of course if the destination of that decision in AAG is Azure Load Balancer, you're simply routing to a uniform set of services, on a specific port, by design. What you put behind there would be up to you.  If it's directly your service, well, then you're port-bound there.  If instead you routed to an ingress controller that was making even more complex decisions (ARR, Traefik, nginx, etc), then you can do so to the extent of the router's capabilities.

Thought 2:
Maybe however you're talking more about traffic shaping (x% here, y% there), if so that logic can be handled by an ingress service behind the Load Balancers. OR, you can add that ingress service in front of the load balancer, but then each of your services would be exposed to the load balancer on a different port.  For traffic treatment, Azure Front Door has some helpful profiles you can build to apply routing rules to your traffic, but you'd still need to handle the "last mile" of ingressing through AAG, and into your LB'ed services.

I could keep guessing at what specifics you might have here, but I'll hand it back to you here at this point to provide some more context around what scenario that we could cover a bit more in this guidance.

**Comment by kudlatiger** [comment] 2020-09-12 04:18
Thanks @ckittel . Let me add a real-time use case.

I have a database which has mapping as shown below

  Customer ID            App Gateway IP      Region
  ----------------------------------------------------
   1 to 100               10.0.0.1                      West US
   100 to 200           10.0.0.2                      West US
   201                      10.0.0.3                      West Europe

> When customer type  www.myappplicationdotcom in the browser, I will redirect him to AAD, and authenticate him
> Once authenticated, I want him to redirect him to the load balancer based on above lookup table 

That's why I call this custom routing 👍

Why do I isolate customer to different infrastructure?
Some Customer does not want to share their data with other customers.  (like customer 201 )
Some Customer does not buy premium package, hence they do not get premium storage (like customer 100 to 200)

**Comment by JasRobe** [comment] 2021-05-19 17:07
@kudlatiger did you get resolution on this issue? I see that it is reasonably old.

**Comment by JasRobe** [comment] 2021-05-21 17:20
closing due to no repsonse.

**Closed by JasRobe** 2021-05-21 17:20 UTC
Labels: Pri2, architecture-center/svc, reference-architecture/subsvc, triaged
