### ISSUE TITLE
not sure if i am violating any terms by creating a structurizr theme with the icons

### ISSUE THREAD

**Issue by dgcaron** [MicrosoftDocs/architecture-center#2822] opened 2021-05-17 19:25 UTC
Hi,

i am in the process of creating a theme for a tool called structurizr and I would like to use the icons provided in the theme. However, I am not sure if I am violating any rules by doing so. can you tell me if I am or not. if I am, I will take the repo down.

i have included a readme in the repo with the proper attribution and included the terms in the repo too.
links:
https://structurizr.com/
https://github.com/dgcaron/structurizr-azure-theme

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment] 2021-05-17 19:25
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/427714/>427714</a>

**Comment by simonbrowndotje** [comment] 2021-05-18 17:04
Perhaps a duplicate of #2251?

**Comment by JasRobe** [comment] 2021-05-21 16:39
Thank you for identifying the duplicate. I'll close this issue.  Good luck with your project!

**Closed by JasRobe** 2021-05-21 16:39 UTC
Labels: architecture-center/svc, assigned-to-author, product-question, triaged
