### ISSUE TITLE
Question regarding the purpose 

### ISSUE THREAD

**Issue by Salamipizza27** [MicrosoftDocs/architecture-center#4156] opened 2023-07-06 13:07 UTC
Not sure if I understood the scenario here properly, but seems like this APIOPS tools are just required if I allow manual changes in the DEV environment, without having the guideline to put the changes into the repositories in form of terraform / bicep code as well. If that is enforced, there is a clean repo that can be deployed to QA and PROD with consistency guaranteed and option of customization through stage dependent variables. Also, this is only related to API Management configurations. If e.g.  a logic app is required in the backend, I need to take care of it in another way.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe11cd6-407f-3dd5-ba44-6a3a51e32943
* Version Independent ID: 6fe11cd6-407f-3dd5-ba44-6a3a51e32943
* Content: [Automated API deployments using APIOps - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/devops/automated-api-deployments-apiops)
* Content Source: [docs/example-scenario/devops/automated-api-deployments-apiops.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/devops/automated-api-deployments-apiops.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @rishabhsaha
* Microsoft Alias: **risaha**

**Comment by ckittel** [comment] 2023-07-06 13:35
Hey there @rishabhsaha, can you help @Salamipizza27 out on your article?

**Comment by rishabhsaha** [comment] 2023-07-06 13:46
Hi, 

> Not sure if I understood the scenario here properly, but seems like this APIOPS tools are just required if I allow manual changes in the DEV environment, without having the guideline to put the changes into the repositories in form of terraform / bicep code as well. If that is enforced, there is a clean repo that can be deployed to QA and PROD with consistency guaranteed and option of customization through stage dependent variables. Also, this is only related to API Management configurations. If e.g. a logic app is required in the backend, I need to take care of it in another way.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 6fe11cd6-407f-3dd5-ba44-6a3a51e32943
> * Version Independent ID: 6fe11cd6-407f-3dd5-ba44-6a3a51e32943
> * Content: [Automated API deployments using APIOps - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/devops/automated-api-deployments-apiops)
> * Content Source: [docs/example-scenario/devops/automated-api-deployments-apiops.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/devops/automated-api-deployments-apiops.yml)
> * Service: **architecture-center**
> * Sub-service: **example-scenario**
> * GitHub Login: @rishabhsaha
> * Microsoft Alias: **risaha**

Hi @Salamipizza27 - APIOps from a conceptual standpoint is focused on having the current state of artifacts deployed in APIM mapped to a Git repository. And it is intended to manage even 1000s of APIs, policies etc at scale. It's essentially GitOps for API lifecycle. We decoupled it from IaC by design, since this is targetted towards artifacts that need to be managed after the base infra has been spun up. You can use the same APIOps principles and use IaC if you are scope is smaller. This link has a step by step workshop and the latest updates around this project: https://azure.github.io/apiops/. Also a recorded video walking through the steps in detail: https://www.youtube.com/watch?v=ID2eGm48oWc

**Comment by AjayBathini-MSFT** [comment] 2023-07-06 17:32
@Salamipizza27 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by ckittel** [comment] 2023-08-11 13:26
#please-close

**Closed by ckittel** 2023-08-11 13:26 UTC
Labels: doc-enhancement, assigned-to-author, triaged, architecture-center/svc, example-scenario/subsvc, Pri1
