### ISSUE TITLE
Wrong content is shown (Cache-Aside is shown for BulkHead)

### ISSUE THREAD

**Issue by sriach2** [MicrosoftDocs/architecture-center#3388] opened 2022-04-12 03:06 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4699b7a-fc21-817e-5a37-aa17b55f47a2
* Version Independent ID: 23efcd5d-11a5-c46f-a73e-5cc638591bcd
* Content: [Bulkhead pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/bulkhead)
* Content Source: [docs/patterns/bulkhead.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/bulkhead.yml)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by MayankBargali-MSFT** [comment] 2022-04-12 12:03
@sriach2 Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by ckittel** [comment] 2022-04-12 20:54
Thank you for catching this, closing as a duplicate of #3387 -- see that issue for remediation being taken.

**Closed by ckittel** 2022-04-12 20:54 UTC
Labels: doc-enhancement, assigned-to-author, triaged, architecture-center/svc, Pri2, design-pattern/subsvc
