### ISSUE TITLE
Local File Name

### ISSUE THREAD

**Issue by EvanMata** [MicrosoftDocs/architecture-center#3173] opened 2021-11-12 23:00 UTC
[Enter feedback here]
Would be useful to show an example that actually grabs the local filename, instead of the user having to manually input it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 647ed505-3e6e-3db7-63ee-025edf6e63f4
* Version Independent ID: d910ba75-6c86-6172-64be-e45ba2bf5a3d
* Content: [Explore data in Azure Blob storage with pandas - Team Data Science Process - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-science-process/explore-data-blob)
* Content Source: [docs/data-science-process/explore-data-blob.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-science-process/explore-data-blob.md)
* Service: **machine-learning**
* Sub-service: **team-data-science-process**
* GitHub Login: @marktab
* Microsoft Alias: **tdsp**

**Comment by david-stanford** [comment] 2021-11-12 23:00
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/517255/>517255</a>

**Comment by SumanthMarigowda** [comment] 2021-11-13 04:38
@EvanMata Thanks for your question. We are checking on this and will respond to you soon.

**Comment by marktab** [comment] 2021-11-15 15:01
@EvanMata Thanks for your question

By design, this example abstracts four variables.  The typical use case is enterprise environments where filenames and parameters may change across systems:

> STORAGEACCOUNTURL= <storage_account_url>
> STORAGEACCOUNTKEY= <storage_account_key>
> LOCALFILENAME= <local_file_name>
> CONTAINERNAME= <container_name>
> BLOBNAME= <blob_name>

The example uses Python's open command.  You may learn how to use Python looking at many free online tutorials or their documentation:  [https://docs.python.org/3/tutorial/inputoutput.html](url)

@SumanthMarigowda  this issue is a Python usage question, and we will not be altering the example which has intentional abstracted fields -- you may close this ticket.

**Closed** 2021-11-17 19:41 UTC
Labels: doc-enhancement, cxp, triaged, machine-learning/svc, team-data-science-process/subsvc
