### ISSUE TITLE
Download documentation for offline

### ISSUE THREAD

**Issue by sy-huss** [MicrosoftDocs/architecture-center#1885] opened 2019-12-17 15:55 UTC
It used to be possible to download this document for offline usage. Now it is not possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4699b7a-fc21-817e-5a37-aa17b55f47a2
* Version Independent ID: 23efcd5d-11a5-c46f-a73e-5cc638591bcd
* Content: [Bulkhead pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/bulkhead)
* Content Source: [docs/patterns/bulkhead.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/bulkhead.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment] 2019-12-18 03:13
Hi @sy-huss Thanks for your feedback. We will review and update as appropriate.

**Comment by absheik** [comment] 2020-01-06 22:04
AB#160200 - Thanks for reporting - this issue is under review

**Comment by doodlemania2** [comment] 2020-04-02 20:17
Duplicate of #1829

**Closed** 2020-04-02 21:12 UTC
Labels: Pri1, architecture-center/svc, assigned-to-author, cloud-fundamentals/subsvc, triaged
