### ISSUE TITLE
azbb -s x-x-x-x -g onprem-vnet-rg -l eastus -p shared-services-stack.json --deploy..... fails!

### ISSUE THREAD

**Issue by djinnah** [MicrosoftDocs/architecture-center#2091] opened 2020-04-20 02:54 UTC
This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.
{'additional_properties': {}, 'code': 'InvalidTemplate', 'message': "Deployment template validation failed: 'The 
I am unable to run this json file and was wondering if there is a fix to the code errors below.  I'm struggling trying to determine how to remediate this error output.

template variable 'virtualMachineTemplate' is not valid: The language expression property 'templateLink' doesn't exist, available properties are 'template, templateHash, parameters, mode, provisioningState'.. Please see https://aka.ms/arm-template-expressions for usage details.'.", 'target': None, 'details': None, 'additional_info': [&lt;azure.mgmt.resource.resources.v2019_07_01.models._models.ErrorAdditionalInfo object at 0x0594C910&gt;]}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87139748-938e-638e-de1f-94f8becfe1da
* Version Independent ID: b96371e6-defb-3e70-792a-2c0cfdc25b7d
* Content: [Implement a hub-spoke network topology - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services)
* Content Source: [docs/reference-architectures/hybrid-networking/shared-services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/shared-services.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment] 2020-04-20 02:54
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#206644

**Comment by f5-applebaum** [comment] 2020-04-22 00:33
Getting same thing. 

"{'additional_properties': {}, 'code': 'InvalidTemplate', 'message': "Deployment template validation failed: 'The template variable 'virtualMachineTemplate' is not valid: The language expression property 'templateLink' doesn't exist, available properties are 'template, templateHash, parameters, mode, provisioningState'.. Please see https://aka.ms/arm-template-expressions for usage details.'.", 'target': None, 'details': None, 'additional_info': [<azure.mgmt.resource.resources.v2019_07_01.models._models_py3.ErrorAdditionalInfo object at 0x107d1ed90>]}"

  error: error executing az
  status: 1
  arguments: group deployment create --name bb-02-vm --subscription XXXXXXX --resource-group onprem-vnet-rg --template-uri https://raw.githubusercontent.com/mspnp/template-building-blocks/v2.2.0/templates/buildingBlocks/virtualMachines/virtualMachines.json --parameters @/Users/username/git/reference-architectures/hybrid-networking/shared-services-stack/shared-services-stack-output-02.json

**Comment by dreampost** [comment] 2020-04-22 20:38
I am getting a different error:
 error: error executing az
  message:
  status: null
  arguments: vm list-skus --resource-type virtualMachines --zone false --subscription <removed_subscription_id>
I read somewhere that buffer level must be added into azCLI.js but it did not help.

**Comment by f5-applebaum** [comment] 2020-04-22 20:49
@dreampost. I ran into that as well. I increased it to "maxBuffer: 1024 * 1024 * 100" per https://github.com/mspnp/template-building-blocks/pull/420/files but still ran into it. Maybe we have a lot of SKUs?  Then tried increasing it again (last num to 1000) and got past that.

**Comment by djinnah** [comment] 2020-04-23 16:20
I did also get past the buffer issue by editing the file as you suggested but the code still has issues with TemplateLink and other code concerns.  Basically, I can’t deploy the code as written and I’m not a developer that understands how to fix it.

**Comment by f5-applebaum** [comment] 2020-04-23 17:12
Yep. to clarify, all I meant to say was with the current code as is,  users will probably run into:

1) https://github.com/mspnp/template-building-blocks/issues/427 
first like @dreampost and I did.  Looks like you did too. However, wanted to re-iterate that the fix in pull request did NOT work for me either ( I had to increase it even more) so note to the owners.  

2) *After* you get past that one, they will run into actual error stated at the top of this issue:

"'The template variable 'virtualMachineTemplate' is not valid: The language expression property 'templateLink' doesn't exist, available properties are 'template, templateHash, parameters, mode, provisioningState'."

ARM Deployments appears to be complaining about this templateLink property:

https://github.com/mspnp/template-building-blocks/blob/v2.2.0/templates/buildingBlocks/virtualMachines/virtualMachines.json#L31

      "properties": {
        "mode": "Incremental",
        "templateLink": {
          "uri": "[variables('virtualMachineTemplate')]"
        },

so the issue is that uri var getting set here:

From:
https://github.com/mspnp/template-building-blocks/blob/v2.2.0/templates/buildingBlocks/virtualMachines/virtualMachines.json#L16

""virtualMachineTemplate": "[concat(uri(deployment().properties.templateLink.uri, 'virtualMachine.json'), parameters('deploymentContext').sasToken)]",

which tries to re-use current template's uri is not getting interpolated correctly. i.e.
concat(uri(deployment().properties.templateLink.uri,
is not actually pointing to:

https://raw.githubusercontent.com/mspnp/template-building-blocks/v2.2.0/templates/buildingBlocks/virtualMachines/

to make the string for the "virtualMachine.json" template they're actually probably trying to reference:
ex.
"https://raw.githubusercontent.com/mspnp/template-building-blocks/v2.2.0/templates/buildingBlocks/virtualMachines/virtualMachine.json"

Could try modifying all these templates to fix the references to nested templates but don't have time. Looks like they just need to fix their links :-)

**Comment by ckittel** [comment] 2020-04-30 21:43
The issue you are experiencing appears to be coming from an upstream behavior change in `az deployment group create` (and the aliased `az group deployment create`).  As of a recent version it now appears to be downloading the `--template-uri` references and sending the downloaded template to the ARM `/validate` endpoint as if it was a local template instead of it being the remote template that it is.  `azbb` uses remote templates for its work.

There is a bug opened for this upstream in az cli to triage.  You can track it at Azure/azure-cli#12990

**Comment by ckittel** [comment] 2020-06-12 19:45
The upstream Azure CLI issue has been fixed and the latest version will properly deference these `templateLink` references now.  As for the `maxBuffer` issue we are tracking that in its own issue.

I'm going to go ahead and close the issue.  If you want to have a continued conversation about other topics, feel free to open up a new issue on them.

Cheers and thank you for brining this to our attention.

**Closed by ckittel** 2020-06-12 19:45 UTC
Labels: Pri1, architecture-center/svc, assigned-to-author, reference-architecture/subsvc, triaged

**Comment by tobystic** [comment] 2020-06-15 22:09
1. (If encountered an error executing az “arguments: vm list-skus...”, an increased buffer size should fix this issue. Please go here to increase buffer size in  C:\Users<userid>\AppData\Roaming\npm\node_modules@mspnp\azure-building-blocks\src\azCli) 
E.g: 
`    spawnOptions = spawnOptions || {
        stdio: 'pipe',
        shell: true,
		maxBuffer : 1024*1024*20`

2. Also note that a most recent stable version of AzCli should be used for this deployment. While I got the error in version 2.5, It ran successfully in 2.7 


3. Finally, If you are using Microsoft free/trial account for this exercise,  the number of VMs created in this exercise is 2 machines more than the required limit per restriction on the free account. The linux VMs can be removed form the spoke VNets. Go to the hub-spoke.json file and delete the linux instances or see this post or visit this [post ](https://github.com/tobystic/reference-architectures/commit/680a09ac2b4ca221fca56f3ac1e4a715234f2168)
