### ISSUE TITLE
Locking down the DB tier.

### ISSUE THREAD

**Issue by g0pinath** [MicrosoftDocs/architecture-center#1731] opened 2019-08-25 00:34 UTC
Can you please clarify if we can lock the DB down, similar to how the function app is locked down.
I know that its possible if the function app is inside an ASE and use SQL Managed instance and set the firewall settings to allow traffic from the ASE subnet, am looking for options for accomplishing this from the function app in consumption plan to a Managed instance SQL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 524d1f97-ce37-f9ac-cf05-d33665eb34df
* Version Independent ID: fe4cc63f-a4b1-c30e-f39f-f4c3de1c57be
* Content: [Serverless web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/serverless/web-app)
* Content Source: [docs/reference-architectures/serverless/web-app.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/serverless/web-app.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment] 2019-08-25 17:41
Hi @g0pinath - Thank you for your feedback! Since this channel for driving improvements towards MS Docs, please share with us the URL of the specific MS Doc that your feedback is most applicable to.

**Comment by g0pinath** [comment] 2019-08-25 23:03
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/serverless/web-app

**Comment by KetanChawda-MSFT** [comment] 2019-08-26 04:37
@g0pinath Can you please clarify what do you mean by locked down here? Do you mean to allow access to DB only from Function App or specific IP's ?

**Comment by g0pinath** [comment] 2019-08-26 05:07
Lock the db to receive traffic only from function apps ip addrress.
Placing the function app inside ASE will solve this but will incur $1100 per
month.

**Comment by KetanChawda-MSFT** [comment] 2019-08-27 04:53
@g0pinath Each function app has a set of available outbound IP addresses. Any outbound connection from a function, such as to a back-end database, uses one of the available outbound IP addresses as the origin IP address. You can't know beforehand which IP address a given connection will use. For this reason, your back-end service must open its firewall to all of the function app's outbound IP addresses.

https://docs.microsoft.com/en-us/azure/azure-functions/ip-addresses#find-outbound-ip-addresses

>When a function app that runs on the Consumption plan is scaled, a new range of outbound IP addresses may be assigned. When running on the Consumption plan, you may need to whitelist the entire data center.

If you need to whitelist the outbound IP addresses used by your function apps, another option is to whitelist the function apps' data center (Azure region). You can [download a JSON file that lists IP addresses for all Azure data centers.](https://www.microsoft.com/en-us/download/details.aspx?id=56519) Then find the JSON fragment that applies to the region that your function app runs in.

**Comment by g0pinath** [comment] 2019-08-27 07:26
Ok but this is not secure as we are opening up our db to all possible
outbound ip addresses rather than just the function app.

How do I just open the firewall port on the db to be accessed only from the
funcrtion app without ASE and this was mu original question.  I was aware
of the possible outbound Ip addresses feature.

**Comment by KetanChawda-MSFT** [comment] 2019-08-27 08:26
@g0pinath  This is the by design with consumption plan , You can consider Function app with App Service plan to get the specific outbound IP range to allow only function App access your DB or the ASE is the option which is costly.

Please check [this](https://docs.microsoft.com/en-us/azure/azure-functions/ip-addresses#dedicated-ip-addresses) document for details

Since there is no doc update required at the moment, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Closed by KetanChawda-MSFT** 2019-08-27 08:26 UTC
Labels: Pri3, architecture-center/svc, cxp, product-question, reference-architecture/subsvc, triaged
