### ISSUE TITLE
Difference in resource type naming prefix or suffix 

### ISSUE THREAD

**Issue by steveculshaw** [MicrosoftDocs/architecture-center#1758] opened 2019-09-03 06:45 UTC
This document shows resource types as suffixes, yet another page (https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/ready/considerations/name-and-tag#recommended-resource-type-prefixes) has the resource types as prefixes

Consistency would be nice :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment] 2019-09-03 10:47
@steveculshaw Thank you for your feedback! Closing this issue as duplicate of https://github.com/MicrosoftDocs/architecture-center/issues/1757

**Closed by KetanChawda-MSFT** 2019-09-03 10:47 UTC
Labels: Pri1, architecture-center/svc, cloud-fundamentals/subsvc, cxp, duplicate, triaged
