### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by iaasazure** [MicrosoftDocs/architecture-center#4091] opened 2023-06-14 19:34 UTC
This content applies to the App Service Environment v2 which is out of date. A Zone redundant ASEv3 has improved this deployment pattern. This design should warn it is for the ASEv2 until it is updated to cater for a zone redundant ASEv3

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c59b0445-0fba-d12e-0c4f-600b9c97aad5
* Version Independent ID: 2d9f8030-b696-651b-b37e-a96b841a4928
* Content: [Enterprise deployment using Azure ASE - Azure Reference Architectures](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/enterprise-integration/ase-standard-deployment)
* Content Source: [docs/reference-architectures/enterprise-integration/ase-standard-deployment.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/enterprise-integration/ase-standard-deployment.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by ManoharLakkoju-MSFT** [comment] 2023-06-15 04:34
@iaasazure 
Duplicate of #https://github.com/MicrosoftDocs/architecture-center/issues/4090

We are going to close this thread as Duplicate https://github.com/MicrosoftDocs/architecture-center/issues/4090

**Closed by ManoharLakkoju-MSFT** 2023-06-15 04:34 UTC
Labels: duplicate, cxp, triaged, architecture-center/svc, reference-architecture/subsvc, Pri2
