### ISSUE TITLE
Medical data Storage Solutions

### ISSUE THREAD

**Issue by keithkambanje** [MicrosoftDocs/architecture-center#1989] opened 2020-02-19 07:46 UTC
Hi, I would like to build a solution for my local hospital.

I need more detailed information about the solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60bc3179-b32b-66c7-40c0-1d5313a4db99
* Version Independent ID: 999cec7f-39f6-f0c2-fd58-56ae4b94bd95
* Content: [Medical Data Storage Solutions - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/medical-data-storage)
* Content Source: [docs/solution-ideas/articles/medical-data-storage.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/medical-data-storage.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment] 2020-02-19 07:46
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#177473

**Comment by absheik** [comment] 2020-02-19 18:07
duplicate of https://github.com/MicrosoftDocs/architecture-center/issues/1988

**Closed by absheik** 2020-02-19 18:07 UTC
Labels: Pri2, architecture-center/svc, cxp, product-question, triaged
