### ISSUE TITLE
"Bulkhead pattern" describes "Cache-Aside" pattern 

### ISSUE THREAD

**Issue by ColeDeanShepherd** [MicrosoftDocs/architecture-center#3384] opened 2022-04-08 16:29 UTC
The ["Bulkhead" pattern page](https://docs.microsoft.com/en-us/azure/architecture/patterns/bulkhead) is currently a duplicate of the ["Cache-Aside" pattern page](https://docs.microsoft.com/en-us/azure/architecture/patterns/cache-aside).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4699b7a-fc21-817e-5a37-aa17b55f47a2
* Version Independent ID: 23efcd5d-11a5-c46f-a73e-5cc638591bcd
* Content: [Bulkhead pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/bulkhead)
* Content Source: [docs/patterns/bulkhead.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/bulkhead.yml)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by KranthiPakala-MSFT** [comment] 2022-04-08 19:29
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by ckittel** [comment] 2022-04-12 20:53
Thank you for catching this, closing as a duplicate of #3387 -- see that issue for remediation being taken.

**Closed by ckittel** 2022-04-12 20:53 UTC
Labels: doc-bug, assigned-to-author, triaged, architecture-center/svc, Pri2, design-pattern/subsvc
