### ISSUE TITLE
Rename Windows Virtual Desktop to: Azure Virtual Desktop

### ISSUE THREAD

**Issue by lukemurraynz** [MicrosoftDocs/architecture-center#2879] opened 2021-06-19 04:46 UTC
Rename Windows Virtual Desktop to: Azure Virtual Desktop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f26be54d-0f67-5098-7839-98f5bb064188
* Version Independent ID: 187fa3ce-ade9-1b07-2af3-c874ec3d0aac
* Content: [Windows Virtual Desktop for the enterprise - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment] 2021-06-19 04:46
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/443766/>443766</a>

**Comment by JayaChatterjee-MSFT** [comment] 2021-07-27 04:24
Duplicate of #2881

**Closed** 2021-07-27 04:24 UTC
Labels: architecture-center/svc, cxp, doc-enhancement, example-scenario/subsvc, triaged
