### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/architecture-center#1366] opened 2019-03-20 04:19 UTC
the link to  Guidelines for Deploying Windows Server Active Directory on Azure Virtual Machines. is dead. it probably means to reference wherever this went: https://github.com/toddkitta/azure-content/blob/master/articles/active-directory/active-directory-deploying-ws-ad-guidelines.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Extend Active Directory Domain Services (AD DS) to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.md)
* Service: **architecture-center**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment] 2019-03-20 16:17
Hi @Mike-Crowley Thank you for reporting this issue! We will review and make any necessary changes.

**Comment by mike-urnun-msft** [comment] 2019-03-25 20:00
Closing as duplicate of #1319

**Closed by mike-urnun-msft** 2019-03-25 20:00 UTC
Labels: cxp, doc-bug, duplicate, triaged
