### ISSUE TITLE
Aug's link is not accessible 

### ISSUE THREAD

**Issue by sharpboy2008** [MicrosoftDocs/architecture-center#2360] opened 2020-08-31 01:21 UTC
[Enter feedback here]
all Aug's link is not accessible
here is one sample
https://docs.microsoft.com/en-us/azure/architecture_architecture-center-pr/docs/solution-ideas/articles/custom-business-processes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd7bc22-da10-1d3b-ba22-7d5e374be441
* Version Independent ID: 9f466c91-adc7-0489-5b1e-17633d27c98c
* Content: [What's New in the Azure Architecture Center - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/changelog#august-2020)
* Content Source: [docs/changelog.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/changelog.md)
* Service: **architecture-center**
* Sub-service: **meta**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment] 2020-08-31 01:21
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#293774

**Comment by cyberjacob** [comment] 2020-09-03 08:54
This is affecting all links on the changelog page, appears to have been caused by 3c14132

**Comment by cyberjacob** [comment] 2020-09-03 08:57
Actually, would suggest closing this as a duplicate of #2342

**Comment by ckittel** [comment] 2020-09-09 17:08
Closing due to dup identified #2342

**Closed by ckittel** 2020-09-09 17:08 UTC
Labels: Pri2, architecture-center/svc, assigned-to-author, doc-bug, meta/subsvc, triaged
