### ISSUE TITLE
Conflicting note and script

### ISSUE THREAD

**Issue by mrochon** [MicrosoftDocs/architecture-center#4173] opened 2023-07-30 18:43 UTC
The first Note in this article says that this scenario assumes existence of a vnet but then the 2nd PS script creates one. What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d61c0c47-bb1e-5bd4-55ed-92058c3c1e2b
* Version Independent ID: 09757b3e-205b-4263-fada-4d0224048f6f
* Content: [Protect APIs with Azure Application Gateway and Azure API Management - Azure Reference Architectures](https://learn.microsoft.com/en-us/azure/architecture/web-apps/api-management/architectures/protect-apis)
* Content Source: [docs/web-apps/api-management/architectures/protect-apis.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/web-apps/api-management/architectures/protect-apis.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @fabriciosanchez
* Microsoft Alias: **robbag**

**Comment by navba-MSFT** [comment] 2023-07-31 04:53
Closing as duplicate of https://github.com/MicrosoftDocs/architecture-center/issues/4174

**Closed by navba-MSFT** 2023-07-31 04:53 UTC
Labels: architecture-center/svc, reference-architecture/subsvc, Pri1
