### ISSUE TITLE
Hope to engage with the creator/contributor of this document

### ISSUE THREAD

**Issue by pinyuko** [MicrosoftDocs/architecture-center#3323] opened 2022-02-25 15:59 UTC
[Enter feedback here]

Hi,

I'm Penny Ko (kopenny) in Microsoft. Azure NetApp Files (ANF) team Arnt de Gier (b-arntdegier) would like to update below 2 documents, but there are no Contributor listed on those documents. Is it possible that you could help to identify the creator of that content and share with us? So Arnt would be able to share feedback and hopefully can reuse the existing Visio file instead of creating one from scratch. Thank you!
1.	https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/sap-dev-test : It has no mention of ANF
2.	https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/sap-production : ANF is only in one sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8307bb37-3a4f-0073-c495-b2aaa4cc8797
* Version Independent ID: 60702144-7610-fda2-a68d-f9f05aff2921
* Content: [SAP workload development and test settings - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/sap-dev-test)
* Content Source: [docs/example-scenario/apps/sap-dev-test.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/apps/sap-dev-test.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @AndrewDibbins
* Microsoft Alias: **pnp**

**Comment by SaurabhSharma-MSFT** [comment] 2022-02-26 01:01
Closing as Duplicate of #3322

**Closed by SaurabhSharma-MSFT** 2022-02-26 01:01 UTC
Labels: doc-enhancement, cxp, triaged, architecture-center/svc, example-scenario/subsvc, Pri2
