### ISSUE TITLE
Fix a hyperlink to "Guide to migrating Big Data workloads to Azure HDInsight"

### ISSUE THREAD

**Issue by arnabganguly** [MicrosoftDocs/architecture-center#4293] opened 2023-11-10 22:28 UTC
It looks like the artifact "Guide to migrating Big Data workloads to Azure HDInsight" in the section **Lift and Shift to HDInsight** is broken. Could you please fix the link? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c269dec-85ae-1519-e309-ae710fff30f4
* Version Independent ID: 7c269dec-85ae-1519-e309-ae710fff30f4
* Content: [Hadoop migration to Azure - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/hadoop/overview)
* Content Source: [docs/guide/hadoop/overview.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/hadoop/overview.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **namratam**

**Comment by SaibabaBalapur-MSFT** [comment] 2023-11-11 05:56
@arnabganguly 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by SaibabaBalapur-MSFT** [comment] 2023-11-11 05:59
@arnabganguly 
Duplicate of https://github.com/MicrosoftDocs/architecture-center/issues/4294

**Closed by SaibabaBalapur-MSFT** 2023-11-11 05:59 UTC
Labels: duplicate, doc-bug, cxp, triaged, Pri3
