### ISSUE TITLE
Problem with shutdown statement - causing customer confusing and concern.

### ISSUE THREAD

**Issue by njsee** [MicrosoftDocs/architecture-center#2619] opened 2021-01-28 18:29 UTC
Hi,
A customer raised an issue around shutting down an Azure hosted domain controllers.
They are worried about this statement:

Do not shut down a domain controller VM using Azure portal. Instead, shut down and restart from the guest operating system. Shutting down through the portal causes the VM to be deallocated, which resets both the VM-GenerationID and the invocationID of the Active Directory repository. This discards the AD DS relative identifier (RID) pool and marks the sysvol folder as nonauthoritative, and may require reconfiguration of the domain controller.

This leads to them not upgrading their Domain controller vms. I feel that this is a non-issue. Can this statement be updated to provide more clarity on the ramifications of deallocating a domain controller and if it truly does cause a problem?

Cheers, Niall

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Deploy AD DS in an Azure virtual network - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by absheik** [comment] 2021-01-28 18:30
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/367449/>367449</a>

**Comment by SatishBoddu-MSFT** [comment] 2021-01-29 03:31
@njsee 
I have assigned the issue to the content author for further review and update the doc as appropriate.

**Comment by Mike-Crowley** [comment] 2021-09-20 17:15
dupe of [2288](https://github.com/MicrosoftDocs/architecture-center/issues/2288) ?

**Comment by RobBagby** [comment] 2022-09-22 19:58
This issue was resolved.

**Closed by RobBagby** 2022-09-22 19:58 UTC
Labels: doc-enhancement, assigned-to-author, triaged, architecture-center/svc, reference-architecture/subsvc, Pri2
